# Generated by Django 3.0.7 on 2020-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
