# Generated by Django 3.0.7 on 2020-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
