# Generated by Django 3.0.7 on 2020-06-07 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scores',
        ),
        migrations.AddField(
            model_name='project',
            name='content_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='design_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='voters',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
