# Generated by Django 3.0.7 on 2020-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200607_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_usabilty',
            field=models.IntegerField(default=0),
        ),
    ]
