# Generated by Django 3.0.7 on 2020-06-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200607_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='average_usabilty',
            new_name='average_usability',
        ),
    ]
