# Generated by Django 3.0.7 on 2020-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200607_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='average_content',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_usability',
            field=models.FloatField(default=0),
        ),
    ]
