# Generated by Django 3.0.7 on 2020-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200607_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
